[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.159.1"
  HUGO_ENVIRONMENT = "production"
  TZ = "America/Sao_Paulo"
  GIT_SUBMODULE_STRATEGY = "none"

[context.production.environment]
  HUGO_ENV = "production"
